[package]
name = "comrak_rustler"
version = "0.1.4"
authors = []
edition = "2021"

[lib]
name = "comrak_rustler"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
typed-arena = "2.0.1"
rustler = "0.30.0"
comrak = { git = "https://github.com/kivikakk/comrak", branch = "akkoma" }
