[package]
name = "comrak"
version = "0.1.0"
authors = ["HansiHE <hansihe@hansihe.com>"]

[lib]
name = "comrak"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.30"
rustler_codegen = "0.30"
comrak = "0.20"
